import os

class Config:
    file_name_regex = r"([a-z]\d{2}-\d{3})[a-z]?.png"
    file_contents_regex = (r"Sentence Database [^\n]*\n+"               # Match the sentence database header. We don't detect the database identifier because it is in the file name and sometimes OCR didn't recognize it properly
                           r"((?:[^\n]+\n)+?)\n+"                       # Matches the clear part of the text (the body)
                           r"(?:[^\n]*\n+)*"                       # Matches the gibberish part of the text (generated by OCR trying to read handwriting)
                           r"Name:")                                    # Matches the name at the end of the text

    class Paths:
        project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

        data_path = os.path.join(project_root, "data")
        sentences_path = os.path.join(data_path, "sentences.json")
        individual_sentences_path = os.path.join(data_path, ".individual_sentences")

    class Colors:
        blue = '\033[94m'
        warning = '\033[93m'
        gray = '\033[90m'
        reset = '\033[0m'
        error = '\033[91m'
