import os

class Config:
    file_name_regex = r"([a-z]\d{2}-\d{3}[a-z]?).png"
    file_contents_regex = (r"Sentence Database [^\n]*\n+"               # Match the sentence database header. We don't detect the database identifier because it is in the file name and sometimes OCR didn't recognize it properly
                           r"((?:[^\n]+\n)+?)\n+"                       # Matches the clear part of the text (the body)
                           r"(?:[^\n]*\n+)*"                       # Matches the gibberish part of the text (generated by OCR trying to read handwriting)
                           r"Name:")                                    # Matches the name at the end of the text

    class Paths:
        project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

        data_path = os.path.join(project_root, "data")
        sentences_path = os.path.join(data_path, "sentences.json")
        individual_sentences_path = os.path.join(data_path, ".individual_sentences")
        images_meta_info_path = os.path.join(data_path, "images_meta_info")
        original_images_path = os.path.join(data_path, "original_data")

        test = os.path.join(data_path, "test")
        test_images = os.path.join(test, "images")
        test_lines = os.path.join(test, "lines")
        test_labels = os.path.join(test, "labels")

        train = os.path.join(data_path, "train")
        train_images = os.path.join(train, "images")
        train_lines = os.path.join(train, "lines")
        train_labels = os.path.join(train, "labels")

        validate = os.path.join(data_path, "validate")
        validate_images = os.path.join(validate, "images")
        validate_lines = os.path.join(validate, "lines")
        validate_labels = os.path.join(validate, "labels")

        sentences_sizes_path = os.path.join(data_path, "sentences_sizes.xml")

    class Colors:
        blue = '\033[94m'
        warning = '\033[93m'
        gray = '\033[90m'
        reset = '\033[0m'
        error = '\033[91m'

    class Data:
        line_width = 512
        line_height = 32

    class Model:
        output_width = 128
